# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_type', models.CharField(choices=[('searching', 'Searching'), ('offering', 'Offering')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact person')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='bulletin_board/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Bulletins',
                'verbose_name': 'Bulletin',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du décès')),
                ('lieu', models.CharField(max_length=100, verbose_name='lieu de décès')),
                ('date_enreg', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'enregistrement")),
                ('cause', models.CharField(max_length=100, verbose_name='cause du décès')),
                ('auteur_certif', models.CharField(max_length=30, verbose_name='Auteur du certificat')),
                ('num_certif', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Numéro du certificat de décès')),
                ('residence', models.CharField(max_length=50, verbose_name='lieu de résidence habituelle du défun')),
                ('residence_mere', models.CharField(max_length=50, verbose_name="lieu de résidence habituelle de la mère pour enfants moin d'un an")),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30, verbose_name='Nom de famille')),
                ('firstname', models.CharField(max_length=30, verbose_name='Prénom(s)')),
            ],
        ),
        migrations.CreateModel(
            name='MortsFoetales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_mere', models.DecimalField(decimal_places=0, max_digits=8, verbose_name="Numéro d'identification de la mère")),
            ],
        ),
        migrations.CreateModel(
            name='Naissances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cert', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Numéro du certificat de naissance')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Poids à la naissance')),
                ('lieu_residence', models.CharField(max_length=50, verbose_name='Lieu de résidence de la mère')),
                ('personne_ass_accouchee', models.CharField(max_length=50, verbose_name="Personne ayant assistée l'accouchée")),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('date_naissance', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('client_name', models.CharField(max_length=1000, verbose_name='Client name')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('M.', 'M.'), ('MME', 'Mme')], default='M.', max_length=3, verbose_name='Civilité')),
                ('lastname', models.CharField(max_length=255, verbose_name='Nom')),
                ('young_girl_lastname', models.CharField(blank=True, max_length=30, verbose_name='Nom de jeune fille')),
                ('firstname', models.CharField(max_length=255, verbose_name='Prénom')),
                ('status', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié'), ('V', 'Veuf')], max_length=15, verbose_name='Stuation matrimoniale')),
                ('sex', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=8, verbose_name='Sexe')),
                ('birthday', models.DateField(verbose_name='Date de naissance')),
                ('birthcity', models.CharField(max_length=255, verbose_name='Ville de naissance')),
                ('nationality', django_countries.fields.CountryField(max_length=2, verbose_name='Pays de naissance')),
                ('job', models.CharField(max_length=30, verbose_name='Profession')),
                ('address', models.CharField(max_length=30, verbose_name='Adresse')),
                ('city', models.CharField(max_length=255, verbose_name='Ville de résidence')),
                ('borough', models.CharField(max_length=30, verbose_name='Arrondissement')),
                ('district', models.CharField(max_length=30, verbose_name='Quartier')),
                ('islet', models.CharField(max_length=30, verbose_name='Îlot')),
                ('plot', models.CharField(max_length=30, verbose_name='Parcelle')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Téléphone')),
                ('mail', models.EmailField(max_length=255, verbose_name='Mail')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('time_elapsed', models.IntegerField(blank=True, default=None, null=True, verbose_name='Elapsed tiem')),
                ('importance', models.IntegerField(verbose_name='Importance')),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='etatcivil.Project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('login', models.CharField(max_length=25, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connection', models.DateField(blank=True, default=None, null=True, verbose_name='date of last connection')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('years_seniority', models.IntegerField(default=0, verbose_name='Seniority')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date of birthday')),
            ],
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etatcivil.Registration')),
                ('num_cert', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Numéro du certificat de naissance')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Poids à la naissance')),
                ('personne_ass_accouchee', models.CharField(max_length=50, verbose_name="Personne ayant assistée l'accouchée")),
                ('birthour', models.TimeField(null=True, verbose_name='Heure de naissance')),
                ('mairie', models.CharField(max_length=30, verbose_name='Mairie')),
            ],
            bases=('etatcivil.registration',),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etatcivil.UserProfile')),
            ],
            bases=('etatcivil.userprofile',),
        ),
        migrations.CreateModel(
            name='Femmes',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etatcivil.Registration')),
            ],
            bases=('etatcivil.registration',),
        ),
        migrations.CreateModel(
            name='Hommes',
            fields=[
                ('registration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etatcivil.Registration')),
            ],
            bases=('etatcivil.registration',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='etatcivil.UserProfile')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specialisation')),
            ],
            bases=('etatcivil.userprofile',),
        ),
        migrations.AddField(
            model_name='naissances',
            name='nip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etatcivil.Registration'),
        ),
        migrations.AddField(
            model_name='deces',
            name='nip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etatcivil.Registration'),
        ),
        migrations.AddField(
            model_name='task',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatcivil.Developer', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='developer',
            name='supervisor_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etatcivil.Supervisor', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='fk_parent1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Parent1', to='etatcivil.Registration', verbose_name='ID parent1'),
        ),
        migrations.AddField(
            model_name='birthcertificate',
            name='fk_parent2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_Parent2', to='etatcivil.Registration', verbose_name='ID parent2'),
        ),
    ]
